language: haskell-stack

env:
  - GHCVER=7.8.4 CABALVER=1.18 STACK_SOLVER=YES
  - GHCVER=7.10.2 CABALVER=1.22 STACK_SOLVER=YES
  - GHCVER=7.8.4 STACK_YAML=stack-lts-2.yaml
  - GHCVER=7.10.2 STACK_YAML=stack-lts-3.yaml
  - GHCVER=7.10.2 STACK_YAML=stack-nightly.yaml
  - GHCVER=head CABALVER=1.22 STACK_SOLVER=YES

matrix:
  fast_finish: true
  allow_failures:
    - env: GHCVER=head CABALVER=1.22 STACK_SOLVER=YES

branches:
  only:
    - master
