# NB: don't set `language: haskell` here

sudo: false

env:
  - GHCVER=7.8.4 STACK_YAML=stack.yaml
  - GHCVER=7.10.1 STACK_YAML=stack-7.10.yaml
  - GHCVER=head STACK_YAML=stack-head.yaml

matrix:
  allow_failures:
    - env: GHCVER=head STACK_YAML=stack-head.yaml

before_install:
  # ghc
  - cat ~/info
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  # versions
  - stack --version
  - ghc --version

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.8.4
    - ghc-7.10.1
    - ghc-head$(sudo id > ~/info)
